

.org 0x80000180

	;; BGM Table
	.byte	NULL,	NULL	;; R300
	.byte	NULL,	NULL	;; R301
	.byte	NULL,	NULL	;; R302
	.byte	NULL,	NULL	;; R303
	.byte	NULL,	NULL	;; R304
	.byte	NULL,	NULL	;; R305
	.byte	NULL,	NULL	;; R306
	.byte	NULL,	NULL	;; R307
	.byte	NULL,	NULL	;; R308
	.byte	NULL,	NULL	;; R309
	.byte	NULL,	NULL	;; R30A
	.byte	NULL,	NULL	;; R30B
	.byte	NULL,	NULL	;; R30C
	.byte	NULL,	NULL	;; R30D
	.byte	NULL,	NULL	;; R30E
	.byte	NULL,	NULL	;; R30F
	.byte	NULL,	NULL	;; R310
	.byte	NULL,	NULL	;; R311
	.byte	NULL,	NULL	;; R312
	.byte	NULL,	NULL	;; R313
	.byte	NULL,	NULL	;; R314
	.byte	NULL,	NULL	;; R315
	.byte	NULL,	NULL	;; R316
	.byte	NULL,	NULL	;; R317
	.byte	NULL,	NULL	;; R318
	.byte	NULL,	NULL	;; R319
	.byte	NULL,	NULL	;; R31A
	.byte	NULL,	NULL	;; R31B
	.byte	NULL,	NULL	;; R31C
	.byte	NULL,	NULL	;; R31D
	.byte	NULL,	NULL	;; R31E
	.byte	NULL,	NULL	;; R31F
	.byte	NULL,	NULL	;; R320
	.byte	NULL,	NULL	;; R321
	.byte	NULL,	NULL	;; R322
	.byte	NULL,	NULL	;; R323
	.byte	NULL,	NULL	;; R324
	.byte	NULL,	NULL	;; R325
	.byte	NULL,	NULL	;; R326
	.byte	NULL,	NULL	;; R327
	.byte	NULL,	NULL	;; R328
	.byte	NULL,	NULL	;; R329
	.byte	NULL,	NULL	;; R32A
	.byte	NULL,	NULL	;; R32B
	.byte	NULL,	NULL	;; R32C
	.byte	NULL,	NULL	;; R32D
	.byte	NULL,	NULL	;; R32E
	.byte	NULL,	NULL	;; R32F
