

.org 0x80000180

	;; BGM Table
	.byte	0x10,	NULL	;; R100	;; SAVE ROOM
	.byte	0x05,	NULL	;; R101	;; 1F LEFT STAIRS
	.byte	0x1A,	NULL	;; R102	;; VACANT ROOM
	.byte	NULL,	NULL	;; R103	;; F PASSAGE
	.byte	0x1A,	NULL	;; R104	;; TEA ROOM
	.byte	0x19,	NULL	;; R105	;; DINING ROOM
	.byte	0x19,	NULL	;; R106	;; HALL
	.byte	0x05,	NULL	;; R107	;; GALLERY
	.byte	0x1A,	NULL	;; R108	;; L PASSAGE
	.byte	NULL,	NULL	;; R109	;; TRAP PASSAGE
	.byte	NULL,	NULL	;; R10A	;; BACK PASSAGE
	.byte	0x19,	NULL	;; R10B	;; 1F RIGHT STAIRS
	.byte	NULL,	NULL	;; R10C	;; GREEN HOUSE
	.byte	NULL,	NULL	;; R10D	;; TIGER STATUE ROOM
	.byte	NULL,	NULL	;; R10E	;; EMPLOYEE ROOM
	.byte	NULL,	NULL	;; R10F	;; BAR
	.byte	NULL,	NULL	;; R110	;; 1F ELEVATOR
	.byte	NULL,	NULL	;; R111	;; DRESSING ROOM
	.byte	NULL,	NULL	;; R112	;; WARDROBE
	.byte	NULL,	NULL	;; R113	;; BATH ROOM
	.byte	NULL,	NULL	;; R114	;; BOILER
	.byte	NULL,	NULL	;; R115	;; TRAP ROOM
	.byte	NULL,	NULL	;; R116	;; LIVING ROOM
	.byte	NULL,	NULL	;; R117	;; LARGE GALLERY
	.byte	0x10,	NULL	;; R118	;; STAIRS UNDER ROOM
	.byte	NULL,	NULL	;; R119	;; STUDY
	.byte	NULL,	NULL	;; R11A	;; ROOFED PASSAGE
	.byte	NULL,	NULL	;; R11B	;; STORE ROOM
	.byte	NULL,	NULL	;; R11C	;; WARDROBE S
	.byte	NULL,	NULL	;; R11D	;; 
	.byte	NULL,	NULL	;; R11E	;; 
	.byte	NULL,	NULL	;; R11F	;; 
	.byte	NULL,	NULL	;; R120	;; 
	.byte	NULL,	NULL	;; R121	;; 
	.byte	NULL,	NULL	;; R122	;; 
	.byte	NULL,	NULL	;; R123	;; 
	.byte	NULL,	NULL	;; R124	;; 
	.byte	NULL,	NULL	;; R125	;; 
	.byte	NULL,	NULL	;; R126	;; 
	.byte	NULL,	NULL	;; R127	;; 
	.byte	NULL,	NULL	;; R128	;; 
	.byte	NULL,	NULL	;; R129	;; 
	.byte	NULL,	NULL	;; R12A	;; 
	.byte	NULL,	NULL	;; R12B	;; 
	.byte	NULL,	NULL	;; R12C	;; 
	.byte	NULL,	NULL	;; R12D	;; 
	.byte	NULL,	NULL	;; R12E	;; 
	.byte	NULL,	NULL	;; R12F	;; 
