@echo OFF

echo Y | DEL ".\\result\\Overlay.txt"
echo Y | DEL ".\\result\\Overlay.log"

utility\bioclone dmyfile 8 ".\\AREA.BIN"
utility\bioclone dmyfile 8 ".\\BIO1.BIN"
utility\bioclone dmyfile 8 ".\\BIO2P.BIN"
utility\bioclone dmyfile 8 ".\\BIO2.BIN"
utility\bioclone dmyfile 8 ".\\BIO3.BIN"
utility\bioclone dmyfile 2048 ".\\BOOT.BIN"
utility\bioclone dmyfile 2048 ".\\DEBUG.BIN"
copy /y ".\\original\\overlay\\DIEDEMO.BIN" ".\\"
utility\bioclone dmyfile 2048 ".\\ZNULL04.BIN"
utility\bioclone dmyfile 2048 ".\\ZNULL05.BIN"
utility\bioclone dmyfile 2048 ".\\ZNULL06.BIN"
utility\bioclone dmyfile 2048 ".\\ZNULL07.BIN"
utility\bioclone dmyfile 2048 ".\\ZNULL08.BIN"
utility\bioclone dmyfile 2048 ".\\ZNULL09.BIN"
utility\bioclone dmyfile 2048 ".\\ZNULL0A.BIN"
utility\bioclone dmyfile 2048 ".\\ZNULL0B.BIN"
utility\bioclone dmyfile 2048 ".\\ZNULL0C.BIN"

armips overlay.s -temp result\\Overlay.txt >> result\\Overlay.log

move /y ".\\AREA.BIN" ".\\disc\\BINARY"
move /y ".\\BIO1.BIN" ".\\disc\\BINARY"
move /y ".\\BIO2P.BIN" ".\\disc\\BINARY"
move /y ".\\BIO2.BIN" ".\\disc\\BINARY"
move /y ".\\BIO3.BIN" ".\\disc\\BINARY"
move /y ".\\BOOT.BIN" ".\\disc\\BINARY"
move /y ".\\DEBUG.BIN" ".\\disc\\BINARY"
move /y ".\\DIEDEMO.BIN" ".\\disc\\BINARY"
move /y ".\\ZNULL04.BIN" ".\\disc\\BINARY"
move /y ".\\ZNULL05.BIN" ".\\disc\\BINARY"
move /y ".\\ZNULL06.BIN" ".\\disc\\BINARY"
move /y ".\\ZNULL07.BIN" ".\\disc\\BINARY"
move /y ".\\ZNULL08.BIN" ".\\disc\\BINARY"
move /y ".\\ZNULL09.BIN" ".\\disc\\BINARY"
move /y ".\\ZNULL0A.BIN" ".\\disc\\BINARY"
move /y ".\\ZNULL0B.BIN" ".\\disc\\BINARY"
move /y ".\\ZNULL0C.BIN" ".\\disc\\BINARY"

C:\bioclone\debug\bioclone align 2048 ".\\disc\\BINARY\\AREA.BIN"
C:\bioclone\debug\bioclone align 2048 ".\\disc\\BINARY\\BIO1.BIN"
C:\bioclone\debug\bioclone align 2048 ".\\disc\\BINARY\\BIO2P.BIN"
C:\bioclone\debug\bioclone align 2048 ".\\disc\\BINARY\\BIO2.BIN"
C:\bioclone\debug\bioclone align 2048 ".\\disc\\BINARY\\BIO3.BIN"
C:\bioclone\debug\bioclone align 2048 ".\\disc\\BINARY\\BOOT.BIN"
C:\bioclone\debug\bioclone align 2048 ".\\disc\\BINARY\\DEBUG.BIN"
C:\bioclone\debug\bioclone align 2048 ".\\disc\\BINARY\\DIEDEMO.BIN"
