@echo OFF

echo Y | DEL ".\\result\\Overlay.txt"
echo Y | DEL ".\\result\\Overlay.log"

utility\test dmyfile 2048 ".\\BIO0.BIN"
utility\test dmyfile 2048 ".\\BIO1.BIN"
utility\test dmyfile 2048 ".\\BIO2P.BIN"
utility\test dmyfile 2048 ".\\BIO2.BIN"
utility\test dmyfile 2048 ".\\BIO3.BIN"
utility\test dmyfile 2048 ".\\BOOT.BIN"
utility\test dmyfile 2048 ".\\DEBUG.BIN"
copy /y ".\\original\\overlay\\CONFIG.BIN" ".\\"
copy /y ".\\original\\overlay\\DIEDEMO.BIN" ".\\"
copy /y ".\\original\\overlay\\ENDING.BIN" ".\\"
copy /y ".\\original\\overlay\\MEM_CARD.BIN" ".\\"
copy /y ".\\original\\overlay\\OPENING.BIN" ".\\"
copy /y ".\\original\\overlay\\RESULT.BIN" ".\\"
copy /y ".\\original\\overlay\\SELECT.BIN" ".\\"
copy /y ".\\original\\overlay\\TITLE.BIN" ".\\"

armips overlay.s -temp result\\Overlay.txt >> result\\Overlay.log

move /y ".\\BIO0.BIN" ".\\disc\\BINARY"
move /y ".\\BIO1.BIN" ".\\disc\\BINARY"
move /y ".\\BIO2P.BIN" ".\\disc\\BINARY"
move /y ".\\BIO2.BIN" ".\\disc\\BINARY"
move /y ".\\BIO3.BIN" ".\\disc\\BINARY"
move /y ".\\BOOT.BIN" ".\\disc\\BINARY"
move /y ".\\DEBUG.BIN" ".\\disc\\BINARY"
move /y ".\\CONFIG.BIN" ".\\disc\\BINARY"
move /y ".\\DIEDEMO.BIN" ".\\disc\\BINARY"
move /y ".\\ENDING.BIN" ".\\disc\\BINARY"
move /y ".\\MEM_CARD.BIN" ".\\disc\\BINARY"
move /y ".\\OPENING.BIN" ".\\disc\\BINARY"
move /y ".\\RESULT.BIN" ".\\disc\\BINARY"
move /y ".\\SELECT.BIN" ".\\disc\\BINARY"
move /y ".\\TITLE.BIN" ".\\disc\\BINARY"

utility\test align 2048 ".\\disc\\BINARY\\BIO0.BIN"
utility\test align 2048 ".\\disc\\BINARY\\BIO1.BIN"
utility\test align 2048 ".\\disc\\BINARY\\BIO2P.BIN"
utility\test align 2048 ".\\disc\\BINARY\\BIO2.BIN"
utility\test align 2048 ".\\disc\\BINARY\\BIO3.BIN"
utility\test align 2048 ".\\disc\\BINARY\\BOOT.BIN"
