

.org 0x80000180

	;; BGM Table
	.byte	0x2B,	NULL	;; R300	;; Factory Entry
	.byte	0x3B,	NULL	;; R301	;; Factory Loading Dock
	.byte	0x3B,	NULL	;; R302	;; Factory Umbrella Front & Lobby
	.byte	0x3A,	NULL	;; R303	;; Factory Assembly Line 2F Entry
	.byte	0x3A,	NULL	;; R304	;; Factory Assembly Line 1F
	.byte	0x3A,	NULL	;; R305	;; Factory Assembly Control Room
	.byte	0x04,	0x06	;; R306	;; Factory Umbrella Back Exit
	.byte	0x1C,	NULL	;; R307	;; Factory Warehouse
	.byte	NULL,	NULL	;; R308	;; Factory Warehouse Elevator
	.byte	0x00,	NULL	;; R309	;; Factory Umbrella Hallway
	.byte	0x3D,	NULL	;; R30A	;; Factory Umbrella Office
	.byte	0x1D,	NULL	;; R30B	;; Macida-Goro-San Parody
	.byte	0x1D,	NULL	;; R30C	;; Factory Umbrella Lobby
	.byte	0x3B,	NULL	;; R30D	;; Factory Umbrella Front Entry
	.byte	NULL,	NULL	;; R30E	;; Factory Warehouse Entry
	.byte	0x3A,	NULL	;; R30F	;; Factory Assembly Line 2F
	.byte	NULL,	NULL	;; R310	;; 
	.byte	NULL,	NULL	;; R311	;; 
	.byte	NULL,	NULL	;; R312	;; 
	.byte	NULL,	NULL	;; R313	;; 
	.byte	NULL,	NULL	;; R314	;; 
	.byte	NULL,	NULL	;; R315	;; 
	.byte	NULL,	NULL	;; R316	;; 
	.byte	NULL,	NULL	;; R317	;; 
	.byte	NULL,	NULL	;; R318	;; 
	.byte	NULL,	NULL	;; R319	;; 
	.byte	NULL,	NULL	;; R31A	;; 
	.byte	NULL,	NULL	;; R31B	;; 
	.byte	NULL,	NULL	;; R31C	;; 
	.byte	NULL,	NULL	;; R31D	;; 
	.byte	NULL,	NULL	;; R31E	;; 
	.byte	NULL,	NULL	;; R31F	;; 
	.byte	NULL,	NULL	;; R320	;; 
	.byte	NULL,	NULL	;; R321	;; 
	.byte	NULL,	NULL	;; R322	;; 
	.byte	NULL,	NULL	;; R323	;; 
	.byte	NULL,	NULL	;; R324	;; 
	.byte	NULL,	NULL	;; R325	;; 
	.byte	NULL,	NULL	;; R326	;; 
	.byte	NULL,	NULL	;; R327	;; 
	.byte	NULL,	NULL	;; R328	;; 
	.byte	NULL,	NULL	;; R329	;; 
	.byte	NULL,	NULL	;; R32A	;; 
	.byte	NULL,	NULL	;; R32B	;; 
	.byte	NULL,	NULL	;; R32C	;; 
	.byte	NULL,	NULL	;; R32D	;; 
	.byte	NULL,	NULL	;; R32E	;; 
	.byte	NULL,	NULL	;; R32F	;; 
