

.org 0x80000180

	;; BGM Table
	.byte	0x28,	NULL	;; R500	;; 
	.byte	NULL,	NULL	;; R501	;; Laboratory Security
	.byte	NULL,	NULL	;; R502	;; Laboratory Command Center
	.byte	0x0B,	NULL	;; R503	;; Laboratory Man-Spider
	.byte	0x27,	NULL	;; R504	;; Laboratory Office
	.byte	0x24,	NULL	;; R505	;; 
	.byte	NULL,	NULL	;; R506	;; 
	.byte	0x27,	NULL	;; R507	;; Laboratory Hallway
	.byte	NULL,	NULL	;; R508	;; 
	.byte	NULL,	NULL	;; R509	;; 
	.byte	NULL,	NULL	;; R50A	;; Laboratory C2 Hanger
	.byte	NULL,	NULL	;; R50B	;; 
	.byte	NULL,	NULL	;; R50C	;; Laboratory Power Hallway
	.byte	NULL,	NULL	;; R50D	;; 
	.byte	NULL,	NULL	;; R50E	;; 
	.byte	NULL,	NULL	;; R50F	;; 
	.byte	NULL,	NULL	;; R510	;; Laboratory Power Hallway
	.byte	NULL,	NULL	;; R511	;; Laboratory Security (Fire)
	.byte	NULL,	NULL	;; R512	;; Laboratory Man-Spider (Fire)
	.byte	NULL,	NULL	;; R513	;; 
	.byte	NULL,	NULL	;; R514	;; Laboratory C2 Hanger (Fire)
	.byte	NULL,	NULL	;; R515	;; 
	.byte	NULL,	NULL	;; R516	;; 
	.byte	NULL,	NULL	;; R517	;; 
	.byte	NULL,	NULL	;; R518	;; 
	.byte	NULL,	NULL	;; R519	;; 
	.byte	NULL,	NULL	;; R51A	;; 
	.byte	NULL,	NULL	;; R51B	;; 
	.byte	NULL,	NULL	;; R51C	;; 
	.byte	NULL,	NULL	;; R51D	;; 
	.byte	NULL,	NULL	;; R51E	;; 
	.byte	NULL,	NULL	;; R51F	;; 
	.byte	NULL,	NULL	;; R520	;; 
	.byte	NULL,	NULL	;; R521	;; 
	.byte	NULL,	NULL	;; R522	;; 
	.byte	NULL,	NULL	;; R523	;; 
	.byte	NULL,	NULL	;; R524	;; 
	.byte	NULL,	NULL	;; R525	;; 
	.byte	NULL,	NULL	;; R526	;; 
	.byte	NULL,	NULL	;; R527	;; 
	.byte	NULL,	NULL	;; R528	;; 
	.byte	NULL,	NULL	;; R529	;; 
	.byte	NULL,	NULL	;; R52A	;; 
	.byte	NULL,	NULL	;; R52B	;; 
	.byte	NULL,	NULL	;; R52C	;; 
	.byte	NULL,	NULL	;; R52D	;; 
	.byte	NULL,	NULL	;; R52E	;; 
	.byte	NULL,	NULL	;; R52F	;; 
