

.org 0x80000180

	;; BGM Table
	.byte	0x28,	NULL	;; R400	;; Laboratory Entry
	.byte	NULL,	NULL	;; R401	;; Laboratory Security
	.byte	0x0F,	NULL	;; R402	;; 
	.byte	NULL,	NULL	;; R403	;; Laboratory Main Shaft
	.byte	0x22,	NULL	;; R404	;; Laboratory Hallway
	.byte	NULL,	NULL	;; R405	;; 
	.byte	NULL,	NULL	;; R406	;; 
	.byte	NULL,	NULL	;; R407	;; 
	.byte	NULL,	NULL	;; R408	;; 
	.byte	NULL,	NULL	;; R409	;; Laboratory Freezer Room
	.byte	NULL,	NULL	;; R40A	;; Laboratory Examination Room
	.byte	NULL,	NULL	;; R40B	;; 
	.byte	NULL,	NULL	;; R40C	;; 
	.byte	NULL,	NULL	;; R40D	;; 
	.byte	NULL,	NULL	;; R40E	;; 
	.byte	NULL,	NULL	;; R40F	;; 
	.byte	NULL,	NULL	;; R410	;; 
	.byte	NULL,	NULL	;; R411	;; 
	.byte	NULL,	NULL	;; R412	;; 
	.byte	NULL,	NULL	;; R413	;; 
	.byte	NULL,	NULL	;; R414	;; 
	.byte	NULL,	NULL	;; R415	;; 
	.byte	NULL,	NULL	;; R416	;; 
	.byte	NULL,	NULL	;; R417	;; 
	.byte	NULL,	NULL	;; R418	;; 
	.byte	NULL,	NULL	;; R419	;; 
	.byte	NULL,	NULL	;; R41A	;; 
	.byte	NULL,	NULL	;; R41B	;; 
	.byte	NULL,	NULL	;; R41C	;; 
	.byte	NULL,	NULL	;; R41D	;; 
	.byte	NULL,	NULL	;; R41E	;; 
	.byte	NULL,	NULL	;; R41F	;; 
	.byte	NULL,	NULL	;; R420	;; 
	.byte	NULL,	NULL	;; R421	;; 
	.byte	NULL,	NULL	;; R422	;; 
	.byte	NULL,	NULL	;; R423	;; 
	.byte	NULL,	NULL	;; R424	;; 
	.byte	NULL,	NULL	;; R425	;; 
	.byte	NULL,	NULL	;; R426	;; 
	.byte	NULL,	NULL	;; R427	;; 
	.byte	NULL,	NULL	;; R428	;; 
	.byte	NULL,	NULL	;; R429	;; 
	.byte	NULL,	NULL	;; R42A	;; 
	.byte	NULL,	NULL	;; R42B	;; 
	.byte	NULL,	NULL	;; R42C	;; 
	.byte	NULL,	NULL	;; R42D	;; 
	.byte	NULL,	NULL	;; R42E	;; 
	.byte	NULL,	NULL	;; R42F	;; 
