

.org 0x80000180

	;; BGM Table
	.byte	0x3D,	NULL	;; R100	;; Introduction PL00
	.byte	0x3D,	NULL	;; R101	;; Introduction PL01
	.byte	0x3E,	NULL	;; R102	;; RPD 1F Office B
	.byte	0x01,	0x00	;; R103	;; RPD 1F Lobby
	.byte	0x3E,	NULL	;; R104	;; RPD 1F Elevator Hallway
	.byte	0x1B,	NULL	;; R105	;; RPD 1F Stairs Hallway
	.byte	NULL,	NULL	;; R106	;; RPD 1F Stairway 1 (!)
	.byte	0x3E,	NULL	;; R107	;; RPD 1F Office A
	.byte	NULL,	NULL	;; R108	;; RPD Elevator (!)
	.byte	0x2F,	NULL	;; R109	;; RPD Outside Back
	.byte	NULL,	NULL	;; R10A	;; RPD 1F Stairway 2 (!)
	.byte	0x2C,	0x1E	;; R10B	;; RPD Outside Front
	.byte	NULL,	NULL	;; R10C	;; 
	.byte	0x1B,	NULL	;; R10D	;; RPD 2F Main Hallway
	.byte	NULL,	NULL	;; R10E	;; 
	.byte	NULL,	NULL	;; R10F	;; 
	.byte	NULL,	NULL	;; R110	;; RPD 2F Archive Access
	.byte	NULL,	NULL	;; R111	;; 
	.byte	0x1A,	NULL	;; R112	;; RPD 3F Elevator Hallway
	.byte	NULL,	NULL	;; R113	;; RPD 3F Main Hallway
	.byte	0x1D,	NULL	;; R114	;; RPD 3F Conference Room
	.byte	NULL,	NULL	;; R115	;; RPD 3F Chief Office
	.byte	0x2C,	0x1E	;; R116	;; RPD 3F Heliport Access
	.byte	0x2C,	0x1E	;; R117	;; RPD Heliport
	.byte	0x39,	NULL	;; R118	;; RPD B1 Main Hallway
	.byte	0x1D,	NULL	;; R119	;; RPD B1 Shooting Range
	.byte	0x1A,	NULL	;; R11A	;; RPD B1 Weapon Storage
	.byte	0x14,	NULL	;; R11B	;; RPD B1 Garage
	.byte	0x16,	NULL	;; R11C	;; RPD B1 Parking Lot
	.byte	NULL,	NULL	;; R11D	;; 
	.byte	0x39,	NULL	;; R11E	;; RPD B2 Main Hallway
	.byte	NULL,	0x07	;; R11F	;; RPD B2 Power Room
	.byte	0x1D,	NULL	;; R120	;; RPD B2 Morgue
	.byte	NULL,	NULL	;; R121	;; RPD B2 Prison Cell
	.byte	NULL,	NULL	;; R122	;; 
	.byte	NULL,	NULL	;; R123	;; 
	.byte	NULL,	NULL	;; R124	;; 
	.byte	NULL,	NULL	;; R125	;; 
	.byte	NULL,	NULL	;; R126	;; 
	.byte	NULL,	NULL	;; R127	;; 
	.byte	NULL,	NULL	;; R128	;; 
	.byte	NULL,	NULL	;; R129	;; 
	.byte	NULL,	NULL	;; R12A	;; 
	.byte	NULL,	NULL	;; R12B	;; 
	.byte	NULL,	NULL	;; R12C	;; 
	.byte	NULL,	NULL	;; R12D	;; 
	.byte	NULL,	NULL	;; R12E	;; 
	.byte	NULL,	NULL	;; R12F	;; 
