

.org 0x80000180

	;; BGM Table
	.byte	NULL,	0x94	;; R600
	.byte	NULL,	NULL	;; R601
	.byte	0x5E,	0xA0	;; R602
	.byte	0x5E,	0xA0	;; R603
	.byte	0x5D,	0xA5	;; R604
	.byte	NULL,	0xA5	;; R605
	.byte	0x22,	NULL	;; R606
	.byte	NULL,	0xD5	;; R607
	.byte	0x22,	0xA7	;; R608
	.byte	NULL,	NULL	;; R609
	.byte	NULL,	NULL	;; R60A
	.byte	0x22,	NULL	;; R60B
	.byte	0x22,	NULL	;; R60C
	.byte	NULL,	NULL	;; R60D
	.byte	NULL,	0x94	;; R60E
	.byte	0x24,	NULL	;; R60F
	.byte	NULL,	NULL	;; R610
	.byte	0x11,	0xA8	;; R611
	.byte	0x22,	NULL	;; R612
	.byte	0x25,	NULL	;; R613
	.byte	0x22,	NULL	;; R614
	.byte	NULL,	0xAD	;; R615
	.byte	0x22,	NULL	;; R616
	.byte	0x52,	0xB4	;; R617
	.byte	NULL,	NULL	;; R618
	.byte	NULL,	NULL	;; R619
	.byte	NULL,	NULL	;; R61A
	.byte	NULL,	NULL	;; R61B
	.byte	NULL,	NULL	;; R61C
	.byte	NULL,	NULL	;; R61D
	.byte	NULL,	NULL	;; R61E
	.byte	NULL,	NULL	;; R61F
	.byte	NULL,	NULL	;; R620
	.byte	NULL,	NULL	;; R621
	.byte	NULL,	NULL	;; R622
	.byte	NULL,	NULL	;; R623
	.byte	NULL,	NULL	;; R624
	.byte	NULL,	NULL	;; R625
	.byte	NULL,	NULL	;; R626
	.byte	NULL,	NULL	;; R627
	.byte	NULL,	NULL	;; R628
	.byte	NULL,	NULL	;; R629
	.byte	NULL,	NULL	;; R62A
	.byte	NULL,	NULL	;; R62B
	.byte	NULL,	NULL	;; R62C
	.byte	NULL,	NULL	;; R62D
	.byte	NULL,	NULL	;; R62E
	.byte	NULL,	NULL	;; R62F
