

.org 0x80000180

	;; BGM Table
	.byte	0x4C,	NULL	;; R400
	.byte	0x0F,	NULL	;; R401
	.byte	0x0C,	NULL	;; R402
	.byte	0x58,	NULL	;; R403
	.byte	0x0F,	0x98	;; R404
	.byte	NULL,	NULL	;; R405
	.byte	0x0F,	0x99	;; R406
	.byte	0x14,	0x18	;; R407
	.byte	0x14,	0x9A	;; R408
	.byte	0x5A,	NULL	;; R409
	.byte	0x1B,	0xC3	;; R40A
	.byte	NULL,	NULL	;; R40B
	.byte	0x17,	NULL	;; R40C
	.byte	0x17,	NULL	;; R40D
	.byte	0x1B,	0xC3	;; R40E
	.byte	0x14,	0xE2	;; R40F
	.byte	NULL,	NULL	;; R410
	.byte	NULL,	NULL	;; R411
	.byte	NULL,	NULL	;; R412
	.byte	NULL,	NULL	;; R413
	.byte	NULL,	NULL	;; R414
	.byte	NULL,	NULL	;; R415
	.byte	NULL,	NULL	;; R416
	.byte	NULL,	NULL	;; R417
	.byte	NULL,	NULL	;; R418
	.byte	NULL,	NULL	;; R419
	.byte	NULL,	NULL	;; R41A
	.byte	NULL,	NULL	;; R41B
	.byte	NULL,	NULL	;; R41C
	.byte	NULL,	NULL	;; R41D
	.byte	NULL,	NULL	;; R41E
	.byte	NULL,	NULL	;; R41F
	.byte	NULL,	NULL	;; R420
	.byte	NULL,	NULL	;; R421
	.byte	NULL,	NULL	;; R422
	.byte	NULL,	NULL	;; R423
	.byte	NULL,	NULL	;; R424
	.byte	NULL,	NULL	;; R425
	.byte	NULL,	NULL	;; R426
	.byte	NULL,	NULL	;; R427
	.byte	NULL,	NULL	;; R428
	.byte	NULL,	NULL	;; R429
	.byte	NULL,	NULL	;; R42A
	.byte	NULL,	NULL	;; R42B
	.byte	NULL,	NULL	;; R42C
	.byte	NULL,	NULL	;; R42D
	.byte	NULL,	NULL	;; R42E
	.byte	NULL,	NULL	;; R42F
