

.org 0x80000180

	;; BGM Table
	.byte	0x0B,	0x01	;; R100
	.byte	0x41,	0xC0	;; R101
	.byte	0x00,	NULL	;; R102
	.byte	0x00,	0x05	;; R103
	.byte	0x0B,	0x01	;; R104
	.byte	0x00,	0x05	;; R105
	.byte	NULL,	0xC3	;; R106
	.byte	0x00,	0x05	;; R107
	.byte	0x00,	0xC2	;; R108
	.byte	0x08,	0xC3	;; R109
	.byte	0x04,	NULL	;; R10A
	.byte	0x08,	NULL	;; R10B
	.byte	0x08,	NULL	;; R10C
	.byte	NULL,	NULL	;; R10D
	.byte	0x08,	NULL	;; R10E
	.byte	0x0C,	NULL	;; R10F
	.byte	0x05,	NULL	;; R110
	.byte	NULL,	0xCB	;; R111
	.byte	0x02,	NULL	;; R112
	.byte	0x08,	NULL	;; R113
	.byte	NULL,	NULL	;; R114
	.byte	0x4D,	NULL	;; R115
	.byte	0x2F,	NULL	;; R116
	.byte	0x05,	NULL	;; R117
	.byte	0x00,	NULL	;; R118
	.byte	0x00,	NULL	;; R119
	.byte	0x29,	NULL	;; R11A
	.byte	0x00,	NULL	;; R11B
	.byte	NULL,	NULL	;; R11C
	.byte	NULL,	NULL	;; R11D
	.byte	NULL,	NULL	;; R11E
	.byte	NULL,	NULL	;; R11F
	.byte	NULL,	NULL	;; R120
	.byte	NULL,	NULL	;; R121
	.byte	NULL,	NULL	;; R122
	.byte	NULL,	NULL	;; R123
	.byte	NULL,	NULL	;; R124
	.byte	NULL,	NULL	;; R125
	.byte	NULL,	NULL	;; R126
	.byte	NULL,	NULL	;; R127
	.byte	NULL,	NULL	;; R128
	.byte	NULL,	NULL	;; R129
	.byte	NULL,	NULL	;; R12A
	.byte	NULL,	NULL	;; R12B
	.byte	NULL,	NULL	;; R12C
	.byte	NULL,	NULL	;; R12D
	.byte	NULL,	NULL	;; R12E
	.byte	NULL,	NULL	;; R12F
