

.org 0x80000180

	;; BGM Table
	.byte	NULL,	NULL	;; R600
	.byte	NULL,	NULL	;; R601
	.byte	NULL,	NULL	;; R602
	.byte	NULL,	NULL	;; R603
	.byte	NULL,	NULL	;; R604
	.byte	NULL,	NULL	;; R605
	.byte	NULL,	NULL	;; R606
	.byte	NULL,	NULL	;; R607
	.byte	NULL,	NULL	;; R608
	.byte	NULL,	NULL	;; R609
	.byte	NULL,	NULL	;; R60A
	.byte	NULL,	NULL	;; R60B
	.byte	NULL,	NULL	;; R60C
	.byte	NULL,	NULL	;; R60D
	.byte	NULL,	NULL	;; R60E
	.byte	NULL,	NULL	;; R60F
	.byte	NULL,	NULL	;; R610
	.byte	NULL,	NULL	;; R611
	.byte	NULL,	NULL	;; R612
	.byte	NULL,	NULL	;; R613
	.byte	NULL,	NULL	;; R614
	.byte	NULL,	NULL	;; R615
	.byte	NULL,	NULL	;; R616
	.byte	NULL,	NULL	;; R617
	.byte	NULL,	NULL	;; R618
	.byte	NULL,	NULL	;; R619
	.byte	NULL,	NULL	;; R61A
	.byte	NULL,	NULL	;; R61B
	.byte	NULL,	NULL	;; R61C
	.byte	NULL,	NULL	;; R61D
	.byte	NULL,	NULL	;; R61E
	.byte	NULL,	NULL	;; R61F
	.byte	NULL,	NULL	;; R620
	.byte	NULL,	NULL	;; R621
	.byte	NULL,	NULL	;; R622
	.byte	NULL,	NULL	;; R623
	.byte	NULL,	NULL	;; R624
	.byte	NULL,	NULL	;; R625
	.byte	NULL,	NULL	;; R626
	.byte	NULL,	NULL	;; R627
	.byte	NULL,	NULL	;; R628
	.byte	NULL,	NULL	;; R629
	.byte	NULL,	NULL	;; R62A
	.byte	NULL,	NULL	;; R62B
	.byte	NULL,	NULL	;; R62C
	.byte	NULL,	NULL	;; R62D
	.byte	NULL,	NULL	;; R62E
	.byte	NULL,	NULL	;; R62F
