

.org 0x80000180

	;; BGM Table
	.byte	NULL,	NULL	;; R200
	.byte	NULL,	NULL	;; R201
	.byte	NULL,	NULL	;; R202
	.byte	NULL,	NULL	;; R203
	.byte	NULL,	NULL	;; R204
	.byte	NULL,	NULL	;; R205
	.byte	NULL,	NULL	;; R206
	.byte	NULL,	NULL	;; R207
	.byte	NULL,	NULL	;; R208
	.byte	NULL,	NULL	;; R209
	.byte	NULL,	NULL	;; R20A
	.byte	NULL,	NULL	;; R20B
	.byte	NULL,	NULL	;; R20C
	.byte	NULL,	NULL	;; R20D
	.byte	NULL,	NULL	;; R20E
	.byte	NULL,	NULL	;; R20F
	.byte	NULL,	NULL	;; R210
	.byte	NULL,	NULL	;; R211
	.byte	NULL,	NULL	;; R212
	.byte	NULL,	NULL	;; R213
	.byte	NULL,	NULL	;; R214
	.byte	NULL,	NULL	;; R215
	.byte	NULL,	NULL	;; R216
	.byte	NULL,	NULL	;; R217
	.byte	NULL,	NULL	;; R218
	.byte	NULL,	NULL	;; R219
	.byte	NULL,	NULL	;; R21A
	.byte	NULL,	NULL	;; R21B
	.byte	NULL,	NULL	;; R21C
	.byte	NULL,	NULL	;; R21D
	.byte	NULL,	NULL	;; R21E
	.byte	NULL,	NULL	;; R21F
	.byte	NULL,	NULL	;; R220
	.byte	NULL,	NULL	;; R221
	.byte	NULL,	NULL	;; R222
	.byte	NULL,	NULL	;; R223
	.byte	NULL,	NULL	;; R224
	.byte	NULL,	NULL	;; R225
	.byte	NULL,	NULL	;; R226
	.byte	NULL,	NULL	;; R227
	.byte	NULL,	NULL	;; R228
	.byte	NULL,	NULL	;; R229
	.byte	NULL,	NULL	;; R22A
	.byte	NULL,	NULL	;; R22B
	.byte	NULL,	NULL	;; R22C
	.byte	NULL,	NULL	;; R22D
	.byte	NULL,	NULL	;; R22E
	.byte	NULL,	NULL	;; R22F
