

.org 0x80000180

	;; BGM Table
	.byte	NULL,	NULL	;; R100
	.byte	NULL,	NULL	;; R101
	.byte	NULL,	NULL	;; R102
	.byte	NULL,	NULL	;; R103
	.byte	NULL,	NULL	;; R104
	.byte	NULL,	NULL	;; R105
	.byte	NULL,	NULL	;; R106
	.byte	NULL,	NULL	;; R107
	.byte	NULL,	NULL	;; R108
	.byte	NULL,	NULL	;; R109
	.byte	NULL,	NULL	;; R10A
	.byte	NULL,	NULL	;; R10B
	.byte	NULL,	NULL	;; R10C
	.byte	NULL,	NULL	;; R10D
	.byte	NULL,	NULL	;; R10E
	.byte	NULL,	NULL	;; R10F
	.byte	NULL,	NULL	;; R110
	.byte	NULL,	NULL	;; R111
	.byte	NULL,	NULL	;; R112
	.byte	NULL,	NULL	;; R113
	.byte	NULL,	NULL	;; R114
	.byte	NULL,	NULL	;; R115
	.byte	NULL,	NULL	;; R116
	.byte	NULL,	NULL	;; R117
	.byte	NULL,	NULL	;; R118
	.byte	NULL,	NULL	;; R119
	.byte	NULL,	NULL	;; R11A
	.byte	NULL,	NULL	;; R11B
	.byte	NULL,	NULL	;; R11C
	.byte	NULL,	NULL	;; R11D
	.byte	NULL,	NULL	;; R11E
	.byte	NULL,	NULL	;; R11F
	.byte	NULL,	NULL	;; R120
	.byte	NULL,	NULL	;; R121
	.byte	NULL,	NULL	;; R122
	.byte	NULL,	NULL	;; R123
	.byte	NULL,	NULL	;; R124
	.byte	NULL,	NULL	;; R125
	.byte	NULL,	NULL	;; R126
	.byte	NULL,	NULL	;; R127
	.byte	NULL,	NULL	;; R128
	.byte	NULL,	NULL	;; R129
	.byte	NULL,	NULL	;; R12A
	.byte	NULL,	NULL	;; R12B
	.byte	NULL,	NULL	;; R12C
	.byte	NULL,	NULL	;; R12D
	.byte	NULL,	NULL	;; R12E
	.byte	NULL,	NULL	;; R12F
