

.org 0x80000180

	;; BGM Table
	.byte	NULL,	NULL	;; R500
	.byte	NULL,	NULL	;; R501
	.byte	NULL,	NULL	;; R502
	.byte	NULL,	NULL	;; R503
	.byte	NULL,	NULL	;; R504
	.byte	NULL,	NULL	;; R505
	.byte	NULL,	NULL	;; R506
	.byte	NULL,	NULL	;; R507
	.byte	NULL,	NULL	;; R508
	.byte	NULL,	NULL	;; R509
	.byte	NULL,	NULL	;; R50A
	.byte	NULL,	NULL	;; R50B
	.byte	NULL,	NULL	;; R50C
	.byte	NULL,	NULL	;; R50D
	.byte	NULL,	NULL	;; R50E
	.byte	NULL,	NULL	;; R50F
	.byte	NULL,	NULL	;; R510
	.byte	NULL,	NULL	;; R511
	.byte	NULL,	NULL	;; R512
	.byte	NULL,	NULL	;; R513
	.byte	NULL,	NULL	;; R514
	.byte	NULL,	NULL	;; R515
	.byte	NULL,	NULL	;; R516
	.byte	NULL,	NULL	;; R517
	.byte	NULL,	NULL	;; R518
	.byte	NULL,	NULL	;; R519
	.byte	NULL,	NULL	;; R51A
	.byte	NULL,	NULL	;; R51B
	.byte	NULL,	NULL	;; R51C
	.byte	NULL,	NULL	;; R51D
	.byte	NULL,	NULL	;; R51E
	.byte	NULL,	NULL	;; R51F
	.byte	NULL,	NULL	;; R520
	.byte	NULL,	NULL	;; R521
	.byte	NULL,	NULL	;; R522
	.byte	NULL,	NULL	;; R523
	.byte	NULL,	NULL	;; R524
	.byte	NULL,	NULL	;; R525
	.byte	NULL,	NULL	;; R526
	.byte	NULL,	NULL	;; R527
	.byte	NULL,	NULL	;; R528
	.byte	NULL,	NULL	;; R529
	.byte	NULL,	NULL	;; R52A
	.byte	NULL,	NULL	;; R52B
	.byte	NULL,	NULL	;; R52C
	.byte	NULL,	NULL	;; R52D
	.byte	NULL,	NULL	;; R52E
	.byte	NULL,	NULL	;; R52F
