

.org 0x80000180

	;; BGM Table
	.byte	NULL,	NULL	;; R700
	.byte	NULL,	NULL	;; R701
	.byte	NULL,	NULL	;; R702
	.byte	NULL,	NULL	;; R703
	.byte	NULL,	NULL	;; R704
	.byte	NULL,	NULL	;; R705
	.byte	NULL,	NULL	;; R706
	.byte	NULL,	NULL	;; R707
	.byte	NULL,	NULL	;; R708
	.byte	NULL,	NULL	;; R709
	.byte	NULL,	NULL	;; R70A
	.byte	NULL,	NULL	;; R70B
	.byte	NULL,	NULL	;; R70C
	.byte	NULL,	NULL	;; R70D
	.byte	NULL,	NULL	;; R70E
	.byte	NULL,	NULL	;; R70F
	.byte	NULL,	NULL	;; R710
	.byte	NULL,	NULL	;; R711
	.byte	NULL,	NULL	;; R712
	.byte	NULL,	NULL	;; R713
	.byte	NULL,	NULL	;; R714
	.byte	NULL,	NULL	;; R715
	.byte	NULL,	NULL	;; R716
	.byte	NULL,	NULL	;; R717
	.byte	NULL,	NULL	;; R718
	.byte	NULL,	NULL	;; R719
	.byte	NULL,	NULL	;; R71A
	.byte	NULL,	NULL	;; R71B
	.byte	NULL,	NULL	;; R71C
	.byte	NULL,	NULL	;; R71D
	.byte	NULL,	NULL	;; R71E
	.byte	NULL,	NULL	;; R71F
	.byte	NULL,	NULL	;; R720
	.byte	NULL,	NULL	;; R721
	.byte	NULL,	NULL	;; R722
	.byte	NULL,	NULL	;; R723
	.byte	NULL,	NULL	;; R724
	.byte	NULL,	NULL	;; R725
	.byte	NULL,	NULL	;; R726
	.byte	NULL,	NULL	;; R727
	.byte	NULL,	NULL	;; R728
	.byte	NULL,	NULL	;; R729
	.byte	NULL,	NULL	;; R72A
	.byte	NULL,	NULL	;; R72B
	.byte	NULL,	NULL	;; R72C
	.byte	NULL,	NULL	;; R72D
	.byte	NULL,	NULL	;; R72E
	.byte	NULL,	NULL	;; R72F
